name: Publish

on:
  push:
    tags: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Yarn install
      run: yarn
    - name: Build shared
      run: yarn build
      working-directory: packages/shared
    - name: Build babel plugin
      run: yarn build
      working-directory: packages/babel-plugin-why-did-you-update
    - name: Build chrome extension
      run: yarn package
      working-directory: packages/extensions
    - name: Publish
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: packages/babel-plugin-why-did-you-update/package.json
